# Generated by Django 2.1.2 on 2018-10-16 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, default=None, help_text='Represents User Birth Date.', verbose_name='Birth Date')),
                ('bio', models.TextField(blank=True, default='Introduction ? Why ?', verbose_name='Biography')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Other'), (1, 'Male'), (2, 'Female')], default=0, verbose_name='Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id', 'user'],
            },
        ),
    ]
