# Generated by Django 2.1.2 on 2018-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False, verbose_name='Email Confirmed'),
        ),
    ]
