# Generated by Django 2.1.2 on 2018-10-23 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_userprofile_email_confirmed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Represents post title.', max_length=255, verbose_name='Title')),
                ('content', models.TextField(help_text='Represents post content.', verbose_name='Content')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='posts', to='users.UserProfile')),
            ],
            options={
                'ordering': ['id', 'title'],
            },
        ),
    ]
